IF /bin/true
	IF /bin/true
		IF /bin/true
			IF /bin/true
				IF /bin/true
					NIF /bin/false
						IF /bin/true
							IF /bin/true
								IF /bin/true
									IF /bin/true
										NIF /bin/false
											echo "@SUCCESS"
